### ISSUE TITLE
Default render, no textures, no glass material?

### ISSUE THREAD

**Issue by zohozer** [appleseedhq/blenderseed#109]
I just installed the latest Blenderseed 0.6 and I opened the Red_interior.blend file in Blender 2.79 and I just pressed the Render button.

Seems that the output is quite different than the one that need to be. Seems that it is missing shaders and textures.

I checked the textures and they are loaded in blender but for some reason they are not assigned to shaders?

Also, another weird thing is that if I press the "appleseed Node" under Surface Shader, the material disappears.

![blenderseed_0 6_defaultrender](https://user-images.githubusercontent.com/5983791/33797312-a983af64-dcfd-11e7-9a54-40e023c07157.PNG)

**Comment by dictoon** [comment]
Looking into it, thanks for the report.

**Comment by dictoon** [comment]
I can reproduce, we're looking into it.

**Comment by dictoon** [comment]
It appears that we somehow broke compatibility with previous .blend files. We're investigating.

**Comment by Narann** [comment]
As we tends to provide various integrations, peoples will start to spend time playing with appleseed in their favourite software. I _think_ we should also start to think about "regression tests suite" into those applications. Open and render some scenes could help. A repo like `blenderseed-regression-test-suite` (`appleseed-max-regression-test-suite`, etc.) or something like this aimed to detect this kind of bug.

It could be a shame to be in the same situation than [Inkscape and Pepper & Carrot](https://www.peppercarrot.com/fr/article396/new-inkscape-0-92-breaks-your-previous-works-done-with-inkscape).

**Comment by dictoon** [comment]
@Narann I completely agree. While we have fully automated, high coverage tests for appleseed itself, we don't have anything automatic for the integrations/plugins at the moment. We do however perform manual regression tests before releases.

The case of blenderseed is slightly different: we decided to move fast and fix many issues post-release, but we're still learning the code base (the plugin was originally written by an exterior contributor) and clearly we broke compatibility unwillingly (and unknowingly). And we failed to perform the most minimal regression tests.

We learned out lesson and will do better next time!

**Comment by dictoon** [comment]
@zohozer We have identified the source of incompatibilities. We were not declaring material properties and rendering settings correctly inside Blender. Unfortunately we have no choice but to break compatibility one more time in the next release. Sorry for that.
