### ISSUE TITLE
blenderseed 0.6.0

### ISSUE THREAD

**Issue by elkingtor** [appleseedhq/blenderseed#110]
Hola blenderseed addon está presentando el siguiente error cuando es llamdo 

![error](https://user-images.githubusercontent.com/34426013/33809769-066440c8-ddca-11e7-83eb-cc032cf591f2.png)

**Comment by dictoon** [comment]
Which version of Blender are you using?

**Comment by elkingtor** [comment]
I am using Version of blnder 2.79
________________________________
De: François Beaune <notifications@github.com>
Enviado: lunes, 11 de diciembre de 2017 2:36 a. m.
Para: appleseedhq/blenderseed
Cc: elkingtor; Author
Asunto: Re: [appleseedhq/blenderseed] blenderseed 0.6.0 (#110)


Which version of Blender are you using?

**Comment by dictoon** [comment]
Thanks.

Your addon folder is called `blenderseed-master`. It needs to be called `blenderseed`. Are you using a git working copy by any chance?
