### ISSUE TITLE
Auto Threads does not properly override the number of rendering threads

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#122]

**Comment by jdent02** [comment]
Everything works as expected on my machine.  Activating 'auto threads' prevents the thread parameter from being emitted.

**Comment by dictoon** [comment]
Yes, the `rendering_threads` parameter is omitted from the project file (which by itself isn't quite correct as I explain below) but it's still not rendering with all threads when Auto Threads is checked, simply because we pass the number of threads to use when invoking appleseed.cli.

Omitting the `rendering_threads` parameter is not the same thing as checking Auto Threads. When a project file does not enforce a given number of threads, the default (machine-specific) configuration is used (`settings/appleseed.cli.xml` or `settings/appleseed.studio.xml` depending on which app you use).

Here is what we need to do:

1. Pass the right number of threads when invoking appleseed.cli: `--threads auto` or `--threads N` where N is the number of threads chosen by the user.
2. Never enforce a number of threads when exporting a scene via File -> Export. That way, the project file is "portable" and will the right number of threads on every machine.

**Comment by jdent02** [comment]
Didn't think of checking the internal render process.  I'll get that fixed tonight (maybe).

**Comment by jdent02** [comment]
#127
