### ISSUE TITLE
Kelemen BRDF specular reflection texture is broken

### ISSUE THREAD

**Issue by vallmoy** [appleseedhq/blenderseed#135]

**Comment by jdent02** [comment]
Specular reflection apparently can't use a texture.  I get an error saying all parameters have to be uniform.

**Comment by dictoon** [comment]
That's correct. It's a limitation of the Kelemen BRDF.

The following inputs must be uniform:

    specular_reflectance
    specular_reflectance_multiplier
    roughness

The following inputs accept textures:

    matte_reflectance
    matte_reflectance_multiplier
