### ISSUE TITLE
Add support for proxies

### ISSUE THREAD

**Issue by ohsnapitsjoel** [appleseedhq/blenderseed#14]
Add support for proxies / loading external .obj's as instances

**Comment by Eneen** [comment]
Any news on this feature?

**Comment by dictoon** [comment]
This hasn't been implemented in Blenderseed, our Blender plugin, that said two things have changed recently:

- That feature is now supported by appleseed core;
- The Blenderseed plugin development was recently resumed thanks to a couple new volunteers joining the team. Interested in helping?

**Comment by Eneen** [comment]
I'm not coder, but of course can help with testing!

**Comment by dictoon** [comment]
Cool, want to join our Slack team? That's where all the development discussions are happening nowadays, for appleseed and the related plugins (including blenderseed). Let me know, I'll be happy to send you an invite by mail.

**Comment by Eneen** [comment]
Please do it.

**Comment by dictoon** [comment]
I would need your email address to send you an invite. You can actually request an invite by clicking on the pink badge that says "slack" on the GitHub page here: https://github.com/appleseedhq/appleseed

**Comment by jdent02** [comment]
I'm going to close this one as archive assemblies can be used in the Python branch

**Comment by mgoldshteyn** [comment]
> Cool, want to join our Slack team? That's where all the development discussions are happening nowadays, for appleseed and the related plugins (including blenderseed). Let me know, I'll be happy to send you an invite by mail.

I would like to get an invite to join your slack channel please send me an invite (mgold10000 at gmail.com)
