### ISSUE TITLE
Render tile buckets are saved with cancelled render

### ISSUE THREAD

**Issue by vallmoy** [appleseedhq/blenderseed#154]
![render tile error](https://user-images.githubusercontent.com/30292603/34454252-b1a321dc-ed67-11e7-8276-6a9a59a5392f.png)

**Comment by jdent02** [comment]
Update: Removing tile highlights works on full image renders.  Border renders however do not.

**Comment by jdent02** [comment]
FYI completion of this is waiting on some modifications to appleseed itself.

**Comment by jdent02** [comment]
Decision was made to remove tile highlighting from the in progress render.

**Comment by jdent02** [comment]
#238
