### ISSUE TITLE
Material Nodes Give Errors on Render (Disney BRDF, Specular BTDF, Diffuse)

### ISSUE THREAD

**Issue by inediblecarrot** [appleseedhq/blenderseed#155]
As far as I can tell the issue is caused by simple naming errors and lack of variable pre-declaration. I was able to fix the errors within these shaders (at least superficially) by simply checking the console log and altering several lines in the file _project_file_writer.py._

The following corrections cause the Disney node shader and a couple others that were broken to work as expected for simple test cases:
file: _project_file_writer.py_ (on Windows, this is a file from the AppData\Roaming directory)
Line 1133: `inputs["Base Coat"]` changed to `inputs["Base Color"]`
Line 1146: `inputs["Base Coat"]` changed to `inputs["Base Color"]`
Line 1940: added variable pre-declarations with default values for `fresnel_multiplier`, `volume_density`, and `volume_scale` (this was done in-line to preserve line numbers for the rest of the file)

There could very well be many other errors related to this particular issue so it's not clear that this basic fix actually addresses an underlying problem.

**Comment by dictoon** [comment]
We actually fixed all this in master. The upcoming version (0.7.0) has a ton of bug fixes and improvements. Stay tuned.

**Comment by inediblecarrot** [comment]
Ah, I see. That's good to hear. I tried installing 0.7.0 before getting 0.6.0 but there was some error in properties\nodes\__init__.py on line 33 that prevented it from installing. Is there a release date for 0.7.0?

**Comment by dictoon** [comment]
Here's a preview of the next release: [blenderseed-0.7.0-preview2.zip](https://github.com/appleseedhq/blenderseed/files/1595853/blenderseed-0.7.0-preview2.zip)

Let us know how it works for you.

We plan to issue a new release of appleseed and all the plugins late next week.

**Comment by jdent02** [comment]
This was solved right?

**Comment by dictoon** [comment]
@inediblecarrot We released blenderseed 0.7.1, this is the version we recommend using as it's been extensively tested:

https://github.com/appleseedhq/blenderseed/releases/tag/v0.7.1

**Comment by inediblecarrot** [comment]
Oh, that's good. I'll try rendering a few things out with it and open a new issue if I find any errors. Thanks for the update
