### ISSUE TITLE
No module named extensions_framework

### ISSUE THREAD

**Issue by abdoubouam** [appleseedhq/blenderseed#163]
When using Blender 2.79.1 (hash : 948515c , date: 25-12-2017), the addon fails to enable.
I found that the folder "extensions_framework" was missing from "<blender_install_path>/2.79/scripts/addons/modules/". 
When copying it from an older build from (2.79.1, 12-09-2017) it started to work properly.

**Comment by jdent02** [comment]
Does it run using the 2.79 release?  We do t have any control over whether the extensions framework module is included as that’s a part of Blender not appleseed

**Comment by dictoon** [comment]
@abdoubouam Which version of blenderseed are you using? Where and how did you download it?

**Comment by dictoon** [comment]
In any case, I'm removing the dependency of blenderseed toward extensions_framework.

**Comment by abdoubouam** [comment]
@dictoon 0.7.0 downloaded from https://github.com/appleseedhq/blenderseed/releases 5 days ago (link found on the official appleseed download page)

**Comment by dictoon** [comment]
@abdoubouam I've uploaded a release of the plugin that no longer depends on `extensions_framework`, see my response in this thread:

https://github.com/appleseedhq/blenderseed/issues/166

could you give it a try please and let us know how it works for you? Thanks!

**Comment by dictoon** [comment]
We release an official fix for this issue in blenderseed 0.7.1:
https://github.com/appleseedhq/blenderseed/releases/tag/v0.7.1
