### ISSUE TITLE
Can't enable appleseed in blendseed 0.7.0 - Blender 2.79

### ISSUE THREAD

**Issue by blademaster7** [appleseedhq/blenderseed#166]
Hi, I just downloaded blendseed 0.70, and Appleseed 1.81 beta, on 2.79, 14-11-2017 build. I installed blendseed as instructed, which seems to work, as the plugin appears in the preferences panel, however when I go enable it, by clicking on the check-box, I get the error message below.

Machine - Win 7 Sp1 - x64.

![appleseed_error](https://user-images.githubusercontent.com/34082930/34912984-e237c68c-f8e7-11e7-895a-fcf6e337df86.png)

Any assistance would be appreciated.

**Comment by dictoon** [comment]
We're heard about this problem from several users, we still don't understand why it only affects some users and not others (and not us, obviously).

We recently removed our dependency to `extensions_framework` but the change didn't make it into blenderseed 0.7.0 for timing reasons. Here is a build that no longer relies on that module:

[blenderseed-0.8.0-preview1.zip](https://github.com/appleseedhq/blenderseed/files/1629175/blenderseed-0.8.0-preview1.zip)

Could you give it a try and let us know here how it works for you?

**Comment by magicusart** [comment]
I also had this problem. With blenderseed-0.8.0, it disappeared.

**Comment by jdent02** [comment]
Were any of you using a daily build of Blender vs 2.79 official?

**Comment by dictoon** [comment]
We release an official fix for this issue in blenderseed 0.7.1:
https://github.com/appleseedhq/blenderseed/releases/tag/v0.7.1
