### ISSUE TITLE
Bump amplitude value is displayed incorrectly

### ISSUE THREAD

**Issue by vallmoy** [appleseedhq/blenderseed#170]
Bump amplitude value is displayed incorrectly below 0.01

![bump 0 001 displayed](https://user-images.githubusercontent.com/30292603/35277260-6fb8609c-0046-11e8-9b0e-1d0f4c3ac531.png)

![bump 0 001](https://user-images.githubusercontent.com/30292603/35277222-4c9c72f6-0046-11e8-88ae-698035728d0b.png)

**Comment by dictoon** [comment]
In #blenderseed on Slack:

jasperge [9:56 AM]
@JonD @franz I just quickly skimmed unread post in this thread. About the UI in Blender not showing all decimals, you can add a `precision` parameter when defining a `FloatProperty`. https://docs.blender.org/api/current/bpy.props.html?highlight=floatproperty#bpy.props.FloatProperty
That way you can say for example that it should always show 3 decimal digits.

**Comment by jdent02** [comment]
#174
