### ISSUE TITLE
Add texture extension controls

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/blenderseed#178]
Blender image tab exposed to blenderseed do not include extension.  Suggest we implement a new texture tab that only includes the options we need.

**Comment by jdent02** [comment]
This is tied to the built in shading system (not OSL).  Is this something even worth spending time on at this point?

**Comment by dictoon** [comment]
I don't really know what this is about, but unless something is really problematic with the built-in materials, we shouldn't invest more time on it. We need to keep what we have fully functional but we shouldn't invest in making it more flexible than it is already.
