### ISSUE TITLE
blenderseed supports Blender 2.79 and up only

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/blenderseed#192]
Due to recent change to using pointer properties on custom parameters, any version of Blender prior to 2.79 will crash.

**Comment by dictoon** [comment]
Blender requirements must be updated everywhere:
- In the code
- In the documentation
- On blenderseed's GitHub home page
- On appleseedhq.net's download page

**Comment by jdent02** [comment]
I think the only one left for this is the main appleseedhq page

**Comment by dictoon** [comment]
Thank you! Web site updated: https://github.com/appleseedhq/appleseedhq.github.io/commit/7bd334a116d747165b5e9e99f55fe8864addebf2
