### ISSUE TITLE
asFresnel node set to Physically Based mode misses input fields

### ISSUE THREAD

**Issue by Mango-3** [appleseedhq/blenderseed#240]
The asFresnel node for Blender misses input fields for (r,g,b) indices of refraction and extinction coefficients  when set to "Physically Based" mode.
![as_fresnel_blender](https://user-images.githubusercontent.com/22252558/39068732-f77376d2-44e5-11e8-8f72-2fb30c2b36d1.PNG)
 
E.g. in Max the input fields for the equivalent node are correctly exposed.
![as_fresnel_max](https://user-images.githubusercontent.com/22252558/39068842-6c35aa80-44e6-11e8-9faa-3484566d5193.PNG)

**Comment by jdent02** [comment]
Found the error.  Turns out I didn't put an option in for vectors in the non-connectable parameters.  I'll fix it up.

Thanks Mango

**Comment by Mango-3** [comment]
Just tested your fix Jonathan. Works well! Setting the IORs for Gold now results in a golden spoon. 
![capture](https://user-images.githubusercontent.com/22252558/39080913-64a47f8a-4540-11e8-8ab9-aad29e6bd87e.PNG)

**Comment by dictoon** [comment]
Fixed!
