### ISSUE TITLE
Verify appleseed path in addon settings menu

### ISSUE THREAD

**Issue by fedormatantsev** [appleseedhq/blenderseed#250]
Add an indicator to notify user if specified directory contains all needed binary files (blenderseed.cli, oslinfo, e.t.c)

**Comment by jdent02** [comment]
I have an idea on how to do this.

**Comment by fedormatantsev** [comment]
You can check renderman add-on code to see how they do this;

**Comment by dictoon** [comment]
Closed because this adds quite a lot of complexity for very little gains. An appleseed release is unlikely to be missing some files but not others. It's either there or it isn't. There's little benefit in adding code to check if particular files are missing.
