### ISSUE TITLE
Interface blocked during rendering

### ISSUE THREAD

**Issue by Rickyc81** [appleseedhq/blenderseed#267]
I'm noticing that, during rendering, the interface hangs, I can not click anything and move the windows of the 3dview

**Comment by jdent02** [comment]
Do you have the lock interface button selected?

**Comment by dictoon** [comment]
Could it also be that all your processor cores are busy rendering and thus leave no time for Blender to update its user interface? Can you try to render with fewer threads? You can adjust the number of rendering threads in blenderseed.

**Comment by dictoon** [comment]
No worries, thanks!
