### ISSUE TITLE
blenderseed material nodes require MSVCR110.dll

### ISSUE THREAD

**Issue by geonom** [appleseedhq/blenderseed#270]
Hi there,

found an issue on my newly reinstalled Win 10 Pro. After installing and setting up blenderseed in Blender 2.79b the material nodes are not selectable - see the attached screenshot. The submenus are empty.

When I restart blender, I get a dozen or so modal windows telling me that MSVCR110.dll is missing. After a quick internet search and installing  Visual C++ Redistributable for Visual Studio 2012 Update 4  it seems to work flawlessly again.

Notes in the installation instructions may be helpful for others as discussed with JonD on discord (thanks for the fast responses :) ).

![screenshot 2](https://user-images.githubusercontent.com/1165081/39872307-db0f0290-5467-11e8-819c-4e6e19af4a63.png)

**Comment by dictoon** [comment]
Fixed. The Windows build of appleseed 1.9.0-beta should no longer rely on MSVCR110.dll.
