### ISSUE TITLE
crash with subsurface modifier

### ISSUE THREAD

**Issue by s-leger** [appleseedhq/blenderseed#271]
Hi,
Experimenting blender crash when objects are using subsurface modifier.
At render time, script export objects until a subsurface modifier is found and then crash.

**Comment by jdent02** [comment]
Can you post screenshots of the console or a printout that shows what the errors are?

Btw are you using adaptive subdivision in Cycles?  If so try turning that off.

**Comment by s-leger** [comment]
Hi, 
hmm, unable to repro now, probably messing something while trying shaders.
Exporter where crashing on a simple object with a subsurf modifier on it 
.
Sorry for trouble, will try to do better next time.

**Comment by dictoon** [comment]
No worries, please create a new ticket if the problem reappears and we'll look into it. Thanks for the feedback!
