### ISSUE TITLE
Blender 2.79b - not loading

### ISSUE THREAD

**Issue by retromore** [appleseedhq/blenderseed#283]
Wanted to try appleseed with blender  2.79b, and same story on 2 machines, windows 10 and windows 8.1. 

* First try after installing add-on + setting directory: no preview is loading for materials.
* Trying to restart, blender is stuck on loading, terminal shows: Parsing OSL shaders...

**Comment by jdent02** [comment]
Are you using the 0.8.1 release or the python_dev branch?

**Comment by retromore** [comment]
The first one, 0.81 beta release

**Comment by jdent02** [comment]
Where is your appleseed directory located?  If it is in Program Files try moving it somewhere else.

Long story short oslinfo is hanging up for some reason.

**Comment by retromore** [comment]
On both machines I tried I just unzipped to desktop.

**Comment by jdent02** [comment]
Sorry if this is a dumb question but you downloaded the 1.9 release of appleseed right?

**Comment by retromore** [comment]
No problem, yeah, just used latest links from the website

**Comment by retromore** [comment]
Ah, it was silly me after all. I set the path to 'Desktop\appleseed' instead of 'Desktop\appleseed\bin'
It works now.

Now I feel a dunce, that I rushed to fill in a bug report. Case closed.
And thanks for leading me to the solution.

**Comment by jdent02** [comment]
No problem. At least it was an easy fix
