### ISSUE TITLE
Python context internal state bug

### ISSUE THREAD

**Issue by oktomus** [appleseedhq/blenderseed#292]
The following message is logged all along when using master blenderseed
```
ERROR: Python context internal state bug. this should not happen!
```

Repro scene : https://drop.oktomus.com/blenderseed-master-repro-scene.zip

**Comment by jdent02** [comment]
Didn't this one get solved?

**Comment by oktomus** [comment]
I don't know, I don't remember if we talked about this or not

**Comment by oktomus** [comment]
There was something about the areaLight not being the correct shader type or something, is that this ?

**Comment by jdent02** [comment]
I'm thinking it turned out to be a glitch cause you were using an older version of appleseed with a newer blenderseed.  Have you seen it occur lately?

**Comment by oktomus** [comment]
I haven't been using blenderseed since. I was using the master branch.

**Comment by jdent02** [comment]
Is this still an issue?

**Comment by dictoon** [comment]
Let's close it, that error hasn't ever been reported since.
