### ISSUE TITLE
Render progress not updated

### ISSUE THREAD

**Issue by Mango-3** [appleseedhq/blenderseed#298]
In Blender the render progress bar and the appleseed rendering pass indicator in the render window are not being updated during rendering (see screenshot taken at pass number 40)
![capture](https://user-images.githubusercontent.com/22252558/43222025-7240b5ac-9057-11e8-8881-756917347cc1.PNG)

**Comment by jdent02** [comment]
What version of the exporter are you using?  As of last night the progress bar worked fine on my copy and that code hasn't been touched in months.

**Comment by Mango-3** [comment]
I use the python-dev version. But maybe it is an issue of my compilation of appleseed-cli that Blender does not get the pass info from it

**Comment by jdent02** [comment]
Fixed with commit b5c7ac381918a24e7eb654d29568e759cf7e31e8
