### ISSUE TITLE
Switch to Datablock ID Properties

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#31]
Datablock ID Properties allow real links to Blender objects like materials, nodetrees, textures etc. This is essential for everyone with a modern linking workflow.

Imagine you have a material with a link to a nodetree. Up to Blender 2.79, the only possibility to store the link to the nodetree in the material was to save the nodetree's name as a string (ugly). Now if this material was linked into another blender scene, the nodetree would not be linked with it automatically - extremely annoying.

Luckily, this problem was adressed in 2.79. See this commit: https://developer.blender.org/D113 and the release logs: https://wiki.blender.org/index.php/Dev:Ref/Release_Notes/2.79/PythonAPI#Data-block_Pointer_Properties

All string-based "links" should eventually be replaced by the new Datablock ID Properties.

**Comment by Theverat** [comment]
Note that implementing this will break backwards compatibility (users will be forced to use blenderseed with Blender 2.79 and upwards).
There's also this problem, mentioned in the release logs linked above:

> ### Forward Compatibility
>Unfortunately, this new custom property type revealed a critical bug in current code, which crashes Blender on unknown property types. This bug has been fixed in 15189baa52 for the future, but it is impossible to fix this for existing releases. 
**This means that trying to load a .blend file using new data-block custom properties will crash on any version prior to 2.79.**

**Comment by jdent02** [comment]
#191
