### ISSUE TITLE
Blenderseed renders nothing

### ISSUE THREAD

**Issue by endersaka** [appleseedhq/blenderseed#310]
I tried: 

1. blenderseed-0.8.0-beta.zip and blenderseed-0.8.1-beta.zip with appleseed-1.8.1-beta-0-gb3b5172-mac64-clang.zip
2. blenderseed-0.7.1.zip with appleseed-1.9.0-beta-0-g5693918-mac64-clang.zip

on a Macbook Pro with Mac OS Sierra 10.12.6.

With this simple scene 
[appleseed_first_render.blend.zip](https://github.com/appleseedhq/blenderseed/files/2295846/appleseed_first_render.blend.zip)

Result is that scene renders in a fraction of a second but it renders nothing.

When I quit Blender (only when appleseed renderer is active, with the scene I've attached) I found this error in the Console app of Mac OS X.

`Aug 17 00:34:00 MacBook-Pro com.apple.xpc.launchd[1] (org.blenderfoundation.blender.18708[5855]): Service exited with abnormal code: 1`

**Comment by dictoon** [comment]
Replied to your post in the forum: unfortunately our macOS builds require a CPU with SSE4.2 instructions support and this appears not to be the case of the CPU in your MacBook Pro.
