### ISSUE TITLE
No rendered mode in viewport shading | Blender

### ISSUE THREAD

**Issue by iamrahatul** [appleseedhq/blenderseed#331]
I downloaded and followed the installation procedure.
Then tried to render but it is not rendering anything, fully blank.
Then tried to see if the rendered mode works or not in viewport shading, but it is not there.

**Comment by jdent02** [comment]
Are you getting any errors in the console?

**Comment by jdent02** [comment]
Also are you using the correct version?  If you downloaded it from Github it is either the 0.8.1 release (that doesn’t have interactive rendering) or the latest source code that doesn’t have appleseed itself packaged with it (only release packages have that)

**Comment by jdent02** [comment]
iamrahatul any feedback on this?

**Comment by dictoon** [comment]
Closing this since no feedback was given and nobody else complained. @iamrahatul please open a new ticket with the requested details if the problem persists.
