### ISSUE TITLE
Sun angle incorrect when tied to rotated environment

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/blenderseed#334]

**Comment by jdent02** [comment]
This appears to be an appleseed issue.  The calculated sun angle is not taking into effect the environment rotation.

**Comment by dictoon** [comment]
Let's keep this bug open, we will need to check that it's working fine in blenderseed once fixed in appleseed (if indeed the bug is on appleseed's side).

**Comment by jdent02** [comment]
Fixed in #387
