### ISSUE TITLE
Catastrophic loss of parallelism at low sampling rates

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#358]
Render a scene with a low number of samples/pixel, e.g. 4 spp. On my 6-core/12-thread machine, rendering seems to be effectively using a single core. It looks as if parallelism is killed by the display of rendered tiles in Blender.

**Comment by jdent02** [comment]
I ran a render with 1spp and I was seeing 100% CPU utilization.

**Comment by jdent02** [comment]
Franz is there a reason to keep this one open?  I haven't been able to reproduce it.

**Comment by dictoon** [comment]
Let's close it.

Thanks for the housekeeping :)
