### ISSUE TITLE
Shading artifacts in glass with scaled objects

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#366]
Bug reported in the forum: https://forum.appleseedhq.net/t/glass-setup/680/

**Comment by jdent02** [comment]
I ran the file through the current master (with C++ export) and I couldn't reproduce the issue.  Like I asked in the thread I'm wondering if he's using a version with the old Python exporter.  It had a different method for exporting normals.

**Comment by jdent02** [comment]
This one hasn't been updated in a while.  I haven't been able to reproduce the issue with the C++ exporter.
