### ISSUE TITLE
SPPM must never be set in interactive configurations

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#373]
blenderseed should never set the lighting engine to SPPM in the interactive configuration, because SPPM only works with final rendering mode.

If SPPM is chosen, blenderseed should still set interactive configuration to use PT.

**Comment by jdent02** [comment]
```python
        lighting_engine = asr_scene_props.lighting_engine if self.export_mode != ProjectExportMode.INTERACTIVE_RENDER else 'pt'
```

This code has been in place for a while.  Is it not working?  Seems to work fine on my system.

**Comment by dictoon** [comment]
The scene attached to [this forum post](https://forum.appleseedhq.net/t/playing-with-sppm/689/12?u=franz) seems to have been generated with blenderseed (I don't know exactly which version, but one recent enough to support SPPM) however the interactive configuration is set to use SPPM.

**Comment by jdent02** [comment]
Ah, that's for the scene export.  Interactive and Final configurations are set simultaneously in the translator.  When you're actually using Blender you can't use SPPM in interactive mode.

**Comment by dictoon** [comment]
I see. That remains a bug that needs to be fixed, right?
