### ISSUE TITLE
Export Blender group instance as an appleseed assembly instance

### ISSUE THREAD

**Issue by gospodnetic** [appleseedhq/blenderseed#38]
Blenderseed exporter does not recognize that and the blender user would have to uninstance the object manually before rendering, resulting in major memory usage.

Add checkbox for object instances: "export as assembly instance" which is by default true
Otherwise the group members should be exported object-by-object.

**Comment by jdent02** [comment]
Being handled as part of python exporter re-write

**Comment by est77** [comment]
This should already work in the python_dev branch. Dupli-groups are exported as assemblies and instanced any number of times needed.
