### ISSUE TITLE
blenderseed fails to load appleseed when double-clicking on a .blend file in Explorer

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#385]
With Blender 2.79b on Windows:

![image](https://user-images.githubusercontent.com/321290/49745799-14478b00-fca0-11e8-8d31-5bee1d7c0a36.png)

![image](https://user-images.githubusercontent.com/321290/49745822-1d385c80-fca0-11e8-8b3a-017ba7d5c4e1.png)

Note that if I open the same file via File -> Open, everything works fine.

**Comment by jdent02** [comment]
What version of blender is in your environment?

**Comment by jdent02** [comment]
i.e. when you click on a .blend where is it going to get the .exe

That error is usually what happens when there's a Python version mis-match

**Comment by jdent02** [comment]
Did you save your user preferences after you enabled appleseed?  If you don't the addon isn't enabled at startup and you'll get these errors.

I should have asked that a while ago.

**Comment by dictoon** [comment]
Since I opened this ticket, I've reinstalled Windows and Blender on my machine. I made sure to save the user settings and I cannot reproduce the error.
