### ISSUE TITLE
DOF focus on Object doesn't work as expected when object is an Empty

### ISSUE THREAD

**Issue by KarthikRIyer** [appleseedhq/blenderseed#389]
when focused on 3D object
![appleseed_render_rook_focus](https://user-images.githubusercontent.com/35020024/49896508-8921ed00-fe79-11e8-81c5-271a5abbbe93.png)
when focused on Empty at same place as that of 3D object
![appleseed_render_empty_focus](https://user-images.githubusercontent.com/35020024/49896565-afe02380-fe79-11e8-8639-d98046d43ad5.png)

**Comment by KarthikRIyer** [comment]
Files
https://drive.google.com/open?id=18XxEbGhE8zqQM-IPbzYRxyQ8Xu53KIly

**Comment by jdent02** [comment]
#391
