### ISSUE TITLE
System parameters should not be emitted when exporting projects

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#390]
This applies to **rendering threads** and **texture cache size**. These should not be written in project files (at least not by default; we could imagine an option to control that behavior).

This is possibly a regression of https://github.com/appleseedhq/blenderseed/issues/232, but I'm not entirely sure: regarding rendering threads, it's important to note that even `auto` should not be emitted in project files.

**Comment by jdent02** [comment]
#391
