### ISSUE TITLE
Strange crash on Linux somehow relating to Mesa/LLVM

### ISSUE THREAD

**Issue by nlburgin** [appleseedhq/blenderseed#397]
I had a crash when trying to enable the 1.0-beta addon, which didn't seem to be at all similar to #349 or #396 or any other listed issue.

I attempted it again running from a terminal (and also with a freshly wiped config folder), and this was the output:

```
$ ./blender
found bundled python: /home/neil/Downloads/blender-2.79b-linux-glibc219-x86_64/2.79/python
addon_utils.disable: blenderseed not disabled.
Modules Installed (blenderseed) from '/home/neil/Downloads/blenderseed-1.0.0-beta-linux64.zip' into '/home/neil/.config/blender/2.79/scripts/addons'
mesa: CommandLine Error: Option 'asan-instrument-assembly' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

I don't know what it means by "inconsistency in registered CommandLine options". Obviously it's not refering to Blender's own command line options, since I didn't use any. I know mesa is my OpenGL driver, and it uses LLVM to output GPU code, but I don't really understand how one of Blender's render plugins could affect their "CommandLine options". 

I tried restarting blender with the included "blender-softwaregl" script, which forces software rendering for OpenGL instead of using the system's actual driver. When running blender this way, the addon enabled and ran just fine, and was able to render a simple scene.

This just a guess, but maybe it's a bug in the code for viewport rendering? FWIW, viewport rendering with appleseed didn't even work in softwareGL-mode; it only showed blank white regardless of the scene contents (see attached screenshot for example). Only regular rendering with F12 worked correctly. 

![viewport-render-of-default-cube-scene](https://user-images.githubusercontent.com/30382228/52258771-5252db00-28ee-11e9-8f50-bb66bcfeb232.png)

Viewport rendering meanwhile still works in BI and Cycles, in both software mode and regular mode, so this doesn't appear to be a systemic problem with my entire OS/blender install. And I made sure the blender install itself was the stock 2.79b download from blender.org, so that shouldn't be the problem.

I really don't know why the plugin would crash blender due to an interaction with the GPU driver, but that appears to be what's happening... In case it helps, I'll mention that my GPU driver is the RadeonSI driver from the standard packaged build of Mesa/Gallium included with Ubuntu 18.04.

**Comment by nlburgin** [comment]
To clarify, that scene in the screenshot that got whited out was the default cube scene.

**Comment by dictoon** [comment]
Thanks for the detailed bug report. I don't think we've ever heard of this problem.

I would guess that the message `inconsistency in registered CommandLine options` means that the LLVM from your OpenGL driver and the one from the appleseed Python module (which is how appleseed is embedded into blenderseed) are incompatible: the two LLVM were built with different command line options. And on Linux, that's a common issue (disclaimer: not a Linux expert).

> I tried restarting blender with the included "blender-softwaregl" script, which forces software rendering for OpenGL instead of using the system's actual driver. When running blender this way, the addon enabled and ran just fine, and was able to render a simple scene.

That was a good thing to test and it confirms my suspicion above.

> viewport rendering with appleseed didn't even work in softwareGL-mode; it only showed blank white regardless of the scene contents (see attached screenshot for example)

That's something we should investigate. I created a new ticket: #398.

(I love your font in Firefox btw!)

**Comment by nlburgin** [comment]
So the problem is that something statically linked into the plugin was conflicting with the system's version? That's interesting. I have no idea how to fix it, but it's interesting.

(In case you're curious, that font is the dialogue font from Paper Mario. I have it set as the default font system-wide for all GTK based apps)
