### ISSUE TITLE
Unable to install addon, several errors. Blender 2.8

### ISSUE THREAD

**Issue by juancarlosgzrz** [appleseedhq/blenderseed#40]
![blenderseed](https://user-images.githubusercontent.com/26150363/30173515-c7301614-93ac-11e7-8520-5bfbde12e2cf.png)

**Comment by juancarlosgzrz** [comment]
Im using latest build of Blender 2.8

**Comment by LucasReSilva** [comment]
I have got the same errors.
![blender_2017-09-07_15-22-15](https://user-images.githubusercontent.com/3827992/30178796-998c8b28-93e0-11e7-8101-ec2c567e28e9.png)

**Comment by LucasReSilva** [comment]
@juancarlosgzrz just remove "-master" from folder name
https://github.com/appleseedhq/blenderseed/wiki/Installation#alternative-manual-installation

**Comment by juancarlosgzrz** [comment]
No, it doesn't work.

**Comment by dictoon** [comment]
@juancarlosgzrz Is this issue still relevant?

**Comment by leonard7e** [comment]
I can confirm, trying to install Blenderseed on blender 1.8.0 (30. 11. 2017 / hash 605ce90c543) gives  an error message.
Using ubuntu Studio.

But, error message looks different to those posted here ...
`... No module named 'extensions_framework'`

![error](https://user-images.githubusercontent.com/5395270/33515811-3b1ba6f2-d768-11e7-9e68-c1c92aff8f2e.png)

**Comment by dictoon** [comment]
Oh, Blender 2.80. Not sure we support this yet. @vallmoy, do you know?

**Comment by dictoon** [comment]
> Modules: extensions_framework was removed.

Ah ok, well that explains it. That means we simply don't support Blender 2.80 yet. Closing this issue and opening another one with the right title.

In the meantime I'd suggest using Blender 2.7x.
