### ISSUE TITLE
Render won't start if the scenes contains an object consisting of just one vertex

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#400]

**Comment by jdent02** [comment]
This is a known issue. It’s been fixed in 2.8

**Comment by dictoon** [comment]
Ok. Is backporting the fix to 2.79 a big deal? If it can be done in minutes, I would suggest to do it; if it depends on refactorings or if it's just too complicated to do, let's not even bother.

**Comment by jdent02** [comment]
It’s a simple check on the length of the objects polygons. Shouldn’t be an issue

**Comment by jdent02** [comment]
There's already a catch for this in the master branch:

if len(obj.data.polygons) > 0:

So I'm not sure what he's seeing or if there's more to the story.

**Comment by jdent02** [comment]
Closing.  This should be handled properly now.
