### ISSUE TITLE
Camera shift not working

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#403]
Reported by [Dez on the forum](https://forum.appleseedhq.net/t/camera-shift-not-working/771).

Test scene: https://mega.nz/#!Ix52wKBI!Sa1fImsrwU69FO8EeHRIO8O90SRmt11tlkSv6BEdxnw

**Comment by jdent02** [comment]
I responded to Dez in Discord a few days ago.

This problem has been fixed in master, but I think he's using 0.8 official.

**Comment by dictoon** [comment]
Thanks for the update.

> edit: Works just fine on my system.

With which version of blenderseed?

Which version (for Blender 2.79) should we recommend Dez to use, and that would have this fix?

**Comment by jdent02** [comment]
I tested against 2.79b (so current master branch).  I want to say that Dez is on Linux though so unless Esteban can put together a build he might be stuck at 1.0.0

**Comment by dictoon** [comment]
Ok, thanks. @est77 any chance of a Linux build of the latest blenderseed (master branch)?

**Comment by jdent02** [comment]
Can we close this one?  Lens shift is fully functional from all the testing I've done.

**Comment by dictoon** [comment]
Let's close it then.
