### ISSUE TITLE
Roughness map bug

### ISSUE THREAD

**Issue by Kumaran7** [appleseedhq/blenderseed#406]
Scene wont render if i connect roughness map to any material shader node.
My spec:  i3,HD 5450 graphics card.

**Comment by dictoon** [comment]
Blender version? blenderseed version? Error message(s)? Which shader node? Without those basic information we cannot help.

**Comment by dictoon** [comment]
Are you the author of [this question](https://forum.appleseedhq.net/t/roughness-map-bug/775/2) on the forum? If so, I suggest to close this ticket.

**Comment by leonard7e** [comment]
Using luminance node to convert color to float, everything works fine.

Could there be a kind of usability bug?
I can connect incompatible node-sockets, without any message or warning from Blenderseed. Some connections work (Float to Color), others dont. 
A feedback about not-working "incompatible socket types" (and suggestion about what to do about it) could help users.
There might be a need for a mechanism which prevents users to create a node graph, which actually wont render.

**Comment by jdent02** [comment]
It’s a restriction of OSL. Normally you can’t connect together two incompatible data types.  There are a few exceptions: float can be hooked into a color input, and similar data types (like color and vector) can be connected.

**Comment by dictoon** [comment]
I agree that this is annoying from a user's point of view.

@jdent02 Could we automatically insert a RGB <-> grayscale conversion node with reasonable defaults when we detect that a grayscale output is connected to an RGB output or vice versa?

**Comment by jdent02** [comment]
Yes, a check could be added to the material translator.  I'll need to do some brainstorming on the best way to implement that.

**Comment by jdent02** [comment]
Point is this isn't a bug so much as a missing feature

**Comment by est77** [comment]
I'd prefer not to add automatic nodes. It is not really correct, we have no way of choosing the right color to grayscale conversion option and if we add support for saving and loading materials at some point, it can be tricky if different plugins start adding invisible virtual nodes everywhere.
Can we prevent the connection being made instead?

**Comment by dictoon** [comment]
I hadn't thought about material export, that's a good point. I'll close this ticket and open a new one about preventing scalar <-> RGB connections, if that's at all possible in Blender.
