### ISSUE TITLE
Prevent scalar <-> RGB connections in shader graph

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#407]
Related to issue #406:

Is it possible in Blender to prevent connecting a RGB node output to a grayscale node input? If not, can we at least emit a clear, visible error message when trying to render a scene with such incorrect connections?

**Comment by leonard7e** [comment]
Jaques Lucke's Animation Nodes could prevent connection of incompatible nodes.

It seems to be possible, but sadly I lack in-depth knowledge on this topic. Found this …

[https://github.com/JacquesLucke/animation_nodes/blob/master/animation_nodes/node_link_conversion.py](https://github.com/JacquesLucke/animation_nodes/blob/master/animation_nodes/node_link_conversion.py)

**Comment by jdent02** [comment]
A signal is triggered whenever a node tree is updated. It would be possible to run a test and either flash an error or break an invalid connection. Once again I’ll have to think of the best way to implement it

**Comment by jdent02** [comment]
FYI this feature is not supportable when using Blender materials' built in nodetree.  If they ever decide to allow custom node trees to be tagged properly for interactive updates then we can switch back and implement this feature.

**Comment by jdent02** [comment]
Closing as it is not implementable with the built in nodetrees.
