### ISSUE TITLE
Blender official 2.79b crash when activating addon

### ISSUE THREAD

**Issue by Kumaran7** [appleseedhq/blenderseed#409]
I am useing linux mint 19.1 xfce.Blenderseed latest version crash when activating the addon in blender 2.79b stable build.

**Comment by jdent02** [comment]
This doesn’t really tell us anything that would help solve your issue. What does the terminal window say when you try to launch it?

**Comment by Kumaran7** [comment]
Nothing complete crash no terminal window

**Comment by Kumaran7** [comment]
There is no teriminal window when i launch blender.

**Comment by Kumaran7** [comment]
Sorry i'm new to linux,now i open blender with terminal and try to enable
appleseed addon and terminal crash with blender.i cant see what terminal
window say.

My system info:CPU: Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
                                   Oerating system:Linux Mint 19.1 Tessa
                                   Graphics card:XFX RADEON HD 5450

**Comment by jdent02** [comment]
Try opening a terminal and launching blender from that. Even when blender crashes they terminal should stay open

**Comment by Kumaran7** [comment]
ok

**Comment by Kumaran7** [comment]
How to install appleseed in maya 2018 windows??

**Comment by jdent02** [comment]
Not really an appropriate thing to discuss here.  Any more information on this issue to share?

**Comment by jdent02** [comment]
Closing for lack of feedback
