### ISSUE TITLE
Can't enable the addon

### ISSUE THREAD

**Issue by Hideaki974** [appleseedhq/blenderseed#42]
the addon doesn't run for me on linux in the 2.79 official build.

same issue as https://forum.appleseedhq.net/t/blender-plugin-wont-work/210

**Comment by dictoon** [comment]
The latest version of the Blender plugin is designed to work with the latest development version of appleseed. It won't work with the latest official version (1.7.0) that I suspect you're using.

We're about to release a new version of appleseed and all the plugins, including the Blender one. Keep an eye on https://appleseedhq.net/ or our Twitter, https://twitter.com/appleseedhq for the announcement!
