### ISSUE TITLE
Add ability to set APPLESEED_SEARCHPATH in user preferences

### ISSUE THREAD

**Issue by jdent02** [appleseedhq/blenderseed#429]

**Comment by est77** [comment]
If we set something, we should append to the APPLESEED_SEARCHPATH env var, never overwrite the value.

**Comment by jdent02** [comment]
That’s the idea. Any paths added will be appended to the env variable and the directory will be immediately scrubbed for any OSL shaders. I’ve got a branch for this one in progress.

**Comment by jdent02** [comment]
#430
