### ISSUE TITLE
unable to render inside blender

### ISSUE THREAD

**Issue by bebinalpha** [appleseedhq/blenderseed#43]
when i try to render  a simple scene it only exports the scene but it doesn't render in blender. i have to open the scene from project folder to render using appleseed.studio.

**Comment by dictoon** [comment]
Yes, the latest version of the Blender plugin requires the latest version of appleseed which is about to be released. Hold on!

**Comment by bebinalpha** [comment]
ok thank you :)

**Comment by bebinalpha** [comment]
Will this new version have AOVs in blender

**Comment by dictoon** [comment]
It won't, but after the 1.8.0 mega-release we will iterate on the various plugins and start filling the gaps.
