### ISSUE TITLE
Cannot enable the addon

### ISSUE THREAD

**Issue by amryounis** [appleseedhq/blenderseed#438]
after installing and when enabling I receive the following:

![image](https://user-images.githubusercontent.com/3895133/62426579-d132a000-b6e6-11e9-85c4-9f9d6052ee4b.png)

**Comment by amryounis** [comment]
blender 2.79

**Comment by jdent02** [comment]
Where did you download the addon?  Also, are you using 2.79b official or a custom build?

**Comment by amryounis** [comment]
activation now works with official 2.79b
