### ISSUE TITLE
State of OSL Script node not retained when saving a Blender scene file

### ISSUE THREAD

**Issue by Mango-3** [appleseedhq/blenderseed#442]
When an OSL script node is used in blenderseed and the file saved as a standard Blender scene file (.blend) the input and output states and UI of the script node are lost. 
Loading such a file shows the script node with Undefined Socket Type (see screenshot) and therefore results in a broken shader network.

![Capture](https://user-images.githubusercontent.com/22252558/63621158-d73be280-c5fb-11e9-828c-7f26147e9d08.PNG)

**Comment by jdent02** [comment]
Long story short this is an issue with Blender (the custom shader nodes losing their classes).  I built a function in that takes care of this issue whenever a file is opened by recompiling any custom shaders but for some reason it isn't working on your setup.  I've never had any problems with it on mine.

Can you check the console when you launch Blender?

**Comment by Mango-3** [comment]
Here is the console output:
![Capture](https://user-images.githubusercontent.com/22252558/63635684-d5126c00-c66d-11e9-9cab-a0cc143068f0.PNG)

**Comment by jdent02** [comment]
Could you provide the .blend?

**Comment by Mango-3** [comment]
A side-note. I used a build-bot version of Blender 2.81. Maybe there had been some changes between 2.80 and 2.81 in Blender with regard to custom shader nodes handling. 
I attached the .blend.
[floor_test_281.zip](https://github.com/appleseedhq/blenderseed/files/3537201/floor_test_281.zip)

**Comment by jdent02** [comment]
Finally took a look at this one.  Something about the Mandlebrot shader is causing the update to fail.  Not sure what or why that's torpedoing the whole thing yet.

**Comment by jdent02** [comment]
Mango, it’s definitely an issue with the Mandelbrot OSL shader, as I can’t get it to compile. When it is removed everything works fine. I’m going to close this issue.
