### ISSUE TITLE
Triplanar mapping is not working correctly

### ISSUE THREAD

**Issue by Asticles** [appleseedhq/blenderseed#451]
Triplanar node seems to break textures when using Frequency.

Using the default uv chart from blender, it breaks the resulting image (see below), when changing the Frequancy parameter to increase image size.

This is how is viewed:
![Screenshot_-_05_09_2019__20_11_40](https://user-images.githubusercontent.com/25231467/64411366-4c43f900-d08d-11e9-95da-36b2968fcdda.png)

And this is how is the map (screenshot):

![Screenshot_-_05_09_2019__20_12_26](https://user-images.githubusercontent.com/25231467/64411537-aa70dc00-d08d-11e9-8f16-13e2ae6b5edd.png)

[triplanar.zip](https://github.com/appleseedhq/blenderseed/files/3582882/triplanar.zip)

**Comment by Asticles** [comment]
Also, note that packed files are not working, you have to unpack them first.

**Comment by jdent02** [comment]
This is more of an appleseed issue.  It should be posted on it's repository

**Comment by dictoon** [comment]
@luisbarrancos What's your opinion on this?

**Comment by luisbarrancos** [comment]
Without more information i can only speculate, but at first glance it seems the user set the coordinate system of the surface point to world space, instead of object space. It's covered in the documentation [here](https://appleseed-maya.readthedocs.io/en/master/shaders/utilities/as_triplanar.html#label-as-triplanar)

**Comment by dictoon** [comment]
I've asked @Asticles on Discord and he tried to plug *Surface Position* into *Surface Point* and change the coordinate system but to no avail.

**Comment by dictoon** [comment]
Here's a full Blender 2.80 scene (based on @Asticles' scene, but with `grid.png` file bundled next to it and setup to repro the problem out of the box):

[triplanarFranz.zip](https://github.com/appleseedhq/blenderseed/files/3819609/triplanarFranz.zip)

Playing with frequency, offset or rotation doesn't seem to have any effect. Maybe I'm missing something obvious, but in that case our users are likely to as well.

**Comment by dictoon** [comment]
Actually, the exported `*.appleseed` file bundled in the ZIP above renders correctly in appleseed.studio:

![image](https://user-images.githubusercontent.com/321290/68390649-09be9b80-0166-11ea-87d6-b835d1b87db2.png)

**Comment by dictoon** [comment]
Well now it works fine even in Blender...

**Comment by dictoon** [comment]
I can no longer reproduce the issue with the `triplanarFranz02.zip` file I posted above. I'm now doubting that I was ever able to reproduce it earlier.

I'm going to close this ticket. Please reopen it if you can reproduce the bug, with the scene I posted or another one.
