### ISSUE TITLE
Packed files are not being rendered

### ISSUE THREAD

**Issue by Asticles** [appleseedhq/blenderseed#452]
Hi all,

Packed images are not rendered.

Expected result (from other issue):

![Screenshot_-_05_09_2019__20_11_40](https://user-images.githubusercontent.com/25231467/64411771-413d9880-d08e-11e9-84f4-752f4d161a8c.png)

Result obtained when packed:

![Screenshot - 06_09_2019 , 10_07_58](https://user-images.githubusercontent.com/25231467/64411800-51557800-d08e-11e9-894b-d71e51bc01da.png)

Sample file:

[triplanar.zip](https://github.com/appleseedhq/blenderseed/files/3582907/triplanar.zip)

**Comment by jdent02** [comment]
This is something that probably can’t be done. When an image is packed, it’s data is added to the .blend file. Cycles has the ability to extract that data directly from the .blend into memory.  Appleseed does not.  It uses file path references to standard image types (.tx, .png, etc).

**Comment by jdent02** [comment]
I don’t consider this a bug.
