### ISSUE TITLE
No light in scene

### ISSUE THREAD

**Issue by CoolOppo** [appleseedhq/blenderseed#462]
Using 2.0.0 beta with blender 2.80 on windows 10 x64, there is no light in my scene. I have tried different types of lights and I've tried path tracing and SPPM.

![image](https://user-images.githubusercontent.com/1498177/66730790-c7819300-ee21-11e9-80df-621f710c32cb.png)

**Comment by leonard7e** [comment]
Hi CoolOppo.
Can you show your material node setup?

**Comment by CoolOppo** [comment]
everything is default. This happens to me if I just use the default scene.

**Comment by jdent02** [comment]
Turn the light intensity up.  The defaults are too low.

**Comment by dictoon** [comment]
> The defaults are too low.

Is it something we can fix?

**Comment by CoolOppo** [comment]
> Turn the light intensity up. The defaults are too low.

There is still no light. I turned the default light up to 10x (the maximum) and there is nothing.

**Comment by leonard7e** [comment]
I think default material uses cycles output node.
If you use cycles material output node, everything renders black. Maybe this problem?

**Comment by dictoon** [comment]
> Can you show your material node setup?

@CoolOppo It would really help if you would show your material setup. As @leonard7e suggested, I strongly suspect that you're using a Cycles output node, and sadly these aren't compatible with appleseed.

**Comment by Eneen** [comment]
I've checked and adding proper appleseed material and surface solves this "issue".
