### ISSUE TITLE
Why doesn't as_texture2surface as asTexture2Surface like other shaders?

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#477]
It appears as `as_texture2surface`:

![image](https://user-images.githubusercontent.com/321290/69922108-5f524380-1499-11ea-8248-66517398d3af.png)

**Comment by jdent02** [comment]
Because it's not a complete shader.

Here's all that's in it:

```

surface as_texture2surface
(
    color in_color = 1,
    float in_scalar = 1
)
{
    Ci = in_color * in_scalar * emission();
}
```

It's missing all the metadata.

**Comment by jdent02** [comment]
This appears to be a Maya based shader for swatches and previews.

**Comment by jdent02** [comment]
Created issue in main appleseed repo
