### ISSUE TITLE
Rename appleseed nodes categories

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#478]
Right appleseed nodes categories are of the form `appleseed-CategoryName` but that's not very aesthetically pleasing.

Some ideas:

- Could we use spaces around the `-`? I.e. `appleseed - CategoryName`
- Or maybe use a `/`? I.e. `appleseed/CategoryName`

I'm open to other suggestions.

**Comment by jdent02** [comment]
I can add spaces between the dashes.
