### ISSUE TITLE
Double sRGB conversion?

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#486]
Here is a cube rendered with the Shading Normals diagnostic mode:

![image](https://user-images.githubusercontent.com/321290/71321829-924b8e00-24bf-11ea-9387-59fd597eb6d7.png)

While the RGB values are correct (they are display when right-clicking in the render) the colors are washed out. It looks like there are two linear-to-sRGB conversions being performed (like, one by appleseed and one by Blender?)

**Comment by jdent02** [comment]
Might be the Filmic view transform as well.

**Comment by dictoon** [comment]
Ah, that's a good point!

**Comment by dictoon** [comment]
That was it, thanks!
