### ISSUE TITLE
Blenderseed not showing up in Render drop down

### ISSUE THREAD

**Issue by huhwutok** [appleseedhq/blenderseed#489]
As the title states, blenderseed is not showing as an option for one of the engines in the dropdown box. There were also some wierd hoops I had to jump through to get it to enable as a plugin (Had to tell blender to install the appleseed.zip that I had downloaded earlier) Now that it's enabled, it seems there is an issue in the __init__py located in "AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blenderseed\render" Blender's console text states 
[appleseed] ERROR: Failed to register class <class 'blenderseed.render.RenderAppleseed'> expected RenderEngine, RenderAppleseed class "view_draw" function to have 2 args, found 3

Previously, this error had occurred with view_update as well, but after much hassle, and eventually reverting the file to it's original text, the error started showing up now for view_draw, rather than view_update. Have no earthly idea whats going on at this point, nor could I fathom why I'd have to add an extra step to the install, figured at this point it couldn't hurt to ask the folks who know what does what.

**Comment by jdent02** [comment]
So it’s indicating that something has been modified in the render __init__ file so that the view_draw function is being called with three arguments instead of the two that it should be. Go into the addon, find the render folder, open the __init__.py file and look for the view_draw function.  Right after the function name there should be the following:

```
(self, context, depsgraph)
```

If it says anything else then the file has been altered.

**Comment by jdent02** [comment]
Btw for the sake of counting the number of arguments being passed, ignore the ‘self’ one

**Comment by huhwutok** [comment]
I've since reinstalled from a fresh download and it's giving me the same issue. Not sure, since I'm not familiar with object oriented in Python,  but would it be possible to remove the "self" argument? I think my next step would be to make a fresh install of blender 2.80, because this plugin is too good to give up on.

**Comment by huhwutok** [comment]
Also, the arguments are exactly as you described

**Comment by jdent02** [comment]
The ‘self’ definitely has to be there, as do the other two. I’d be curious to see what happens if you delete the addon manually.  Try going into ‘AppData/Roaming/Blender Foundation/2.8/scripts/addons’ and delete the blenderseed folder.

**Comment by jdent02** [comment]
FYI, ‘self’ has to be in the argument list any time a function references anything in the class it’s a part of.

**Comment by huhwutok** [comment]
Yep, same issue from a fresh install of the plugin

**Comment by jdent02** [comment]
I would delete the AppData folder as well so you have a completely blank slate.

It goes without saying that I’m not having this error on my machine.  I do use Blender 2.81 but I don’t think the function signature of view_update was changed. I’ll check quickly.

**Comment by huhwutok** [comment]
So, from a fresh install of 2.80, non-beta, deleting the appdata folder, and grabbing a fresh download of the plugin, I received this 
![FromEnable](https://user-images.githubusercontent.com/59488233/71755787-0b4ccd00-2e52-11ea-9282-82cab88b1de8.png)

**Comment by huhwutok** [comment]
At this point, I think my computer is just haunted :/

**Comment by jdent02** [comment]
Well appleseed is 64 bit only. That might be part of the problem....

**Comment by huhwutok** [comment]
Odd, maybe  I accidentally installed the 32 version of blender

**Comment by huhwutok** [comment]
UPDATE: Installed the 64 bit version of 2.80. Seems my initial issue the first time around is that while I technically using 2.80, I was using the beta version from the initial release.

**Comment by jdent02** [comment]
So it’s working properly now?

**Comment by huhwutok** [comment]
Everything would be,  now just to stop the crashes with  live preview,  and familiarize myself with the shader system
