### ISSUE TITLE
"OSL Script Base" node doesn't work when shaders have #include

### ISSUE THREAD

**Issue by laurelkeys** [appleseedhq/blenderseed#494]
After loading a script from [`appleseed.shaders/src/appleseed/`](https://github.com/appleseedhq/appleseed/tree/master/src/appleseed.shaders/src/appleseed) into the **OSL Script Base** node, it seems like it's only be able to "Create Parameters" when the shader doesn't have any `#include` directives. Otherwise, it reports a "OSL script did not compile!" error (see attached image).

I tested the following `.osl` files:
- Worked: `as_matte`, `as_glass` and `as_disney_material`
- Didn't work: `as_metal`, `as_toon` and `as_standard_surface`

![oslbuilderror](https://user-images.githubusercontent.com/13294013/76908118-bd5b3900-6886-11ea-900d-097fcaf01351.png)

**Comment by dictoon** [comment]
@jdent02 @est77 Could this be that search paths for include files aren't set properly?

**Comment by jdent02** [comment]
There doesn't appear to be a way to specify #include directories in the render time shader compiler.  At least not one that's exposed yet.  There's a way to set the path to stdosl but that's it.

**Comment by jdent02** [comment]
It isn't included no.  I can add the option.

**Comment by jdent02** [comment]
After discussion with Esteban, for portability it wouldn't be a good idea to include the ability to set #include paths for custom shaders.

**Comment by jdent02** [comment]
Closed as it was decided not to implement this.
