### ISSUE TITLE
Display buckets during rendering

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#50]

**Comment by jdent02** [comment]
Here's the relevant code from Luxrender:

def draw_tiles(self, scene, stats, imageBuffer, filmWidth, filmHeight):
        """
        draws tile outlines directly into the imageBuffer

        scene: Blender scene object
        stats: LuxCore stats (from LuxCore session)
        imageBuffer: list of tuples of floats, e.g. [(r, g, b, a), ...], must be sliceable!
        """
        tile_size = scene.luxcore_enginesettings.tile_size
        show_converged = scene.luxcore_tile_highlighting.show_converged
        show_unconverged = scene.luxcore_tile_highlighting.show_unconverged
        show_pending = scene.luxcore_tile_highlighting.show_pending

        def draw_tile_type(count, coords, color):
            """
            draws all tiles at the given coordinates with given color
            """
            for i in range(count):
                offset_x = coords[i * 2]
                offset_y = coords[i * 2 + 1]
                width = min(tile_size + 1, filmWidth - offset_x)
                height = min(tile_size + 1, filmHeight - offset_y)

                draw_tile_outline(offset_x, offset_y, width, height, color)

        def draw_tile_outline(offset_x, offset_y, width, height, color):
            """
            draws the outline of one tile
            """
            for y in range(offset_y, offset_y + height):
                sliceStart = y * filmWidth + offset_x
                sliceEnd = sliceStart + width

                if y == offset_y or y == offset_y + height - 1:
                    # bottom and top lines
                    imageBuffer[sliceStart:sliceEnd] = [color] * width
                else:
                    # left and right sides
                    imageBuffer[sliceStart] = color
                    try:
                        imageBuffer[sliceEnd - 1] = color
                    except IndexError:
                        # catch this so render does not crash when we try to draw outside the imageBuffer
                        # (should not be possible anymore, but leave it in in case there's an unknown bug)
                        pass

**Comment by dictoon** [comment]
Done in #123.
