### ISSUE TITLE
Allow using textures packed in .blend file, or automatically unpack them

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/blenderseed#52]

**Comment by jdent02** [comment]
If we're going to remove the BSDF hooks to the internal texture system this will not be an option.

**Comment by jdent02** [comment]
Suggest we close this one as new exporter doesn't use Blenders texturing system

**Comment by dictoon** [comment]
I'm not sure to understand: regardless of the texture system being used, if there are textures packed inside the .blend file, maybe the user wants to use them?

**Comment by jdent02** [comment]
That would require using Blender's texture system.  The way packing works is if you have textures that are being used in the texturing system, you can pack them into .blend files.  If you aren't using the texturing system there's nothing to pack.

**Comment by jdent02** [comment]
Also, if the file comes with textures already packed in it. the user can already use those by choosing to unpack the file, in which case it'll create image files in a location of their choosing.

**Comment by dictoon** [comment]
I think that was the spirit of this ticket: automatically unpack textures that are going to be required by the render.

**Comment by jdent02** [comment]
Mostly handled with 87bcacb9a06642302ba4d35a55563b73398fd79e

There doesn't appear to be a way to directly use packed textures.
