### ISSUE TITLE
Blender 2.9x and above - addon doesn't install

### ISSUE THREAD

**Issue by Gluke79** [appleseedhq/blenderseed#526]
Tried installing the addon in 2.93 and 3.0 and it doesn't let install.

Here is the reported error in 2.93:

![image](https://user-images.githubusercontent.com/57181019/119478709-51107b00-bd50-11eb-99a9-08a64f1303da.png)

**Comment by jdent02** [comment]
I believe Blender 2.93 has moved to Python 3.8.  Our bindings for appleseed max out at Python 3.7 currently.
