### ISSUE TITLE
Hiba blender 2.93 

### ISSUE THREAD

**Issue by Linuxfun1990** [appleseedhq/blenderseed#527]
[
![JzcxKmg6qW](https://user-images.githubusercontent.com/49381141/127784189-afcfb552-8aa5-4056-be9b-ee9926438d69.png)
](url)

Install render plugin Appleeed 2.1.0-beta or blender plugin enable plugin chrashed

**Comment by jdent02** [comment]
Appleseed does not have Python 3.9 functionality so Blender 2.93 and up will not work at this time.
