### ISSUE TITLE
Remove deprecated Microfacet BRDF

### ISSUE THREAD

**Issue by vallmoy** [appleseedhq/blenderseed#78]
Doesn't display in material preview. 
Error: invalid model "microfacet_brdf"

**Comment by jdent02** [comment]
Wasn't microfacet removed from appleseed?  It's not in the built in entities list.

**Comment by dictoon** [comment]
It was, yes.

**Comment by jdent02** [comment]
Well it would make sense that its broken in blenderseed then :)

**Comment by jdent02** [comment]
I'll roll this into my BSDF tasks.

**Comment by dictoon** [comment]
Ok, changing the title of the issue.

**Comment by jdent02** [comment]
#87
