### ISSUE TITLE
Add material thumbnail

### ISSUE THREAD

**Issue by vallmoy** [appleseedhq/blenderseed#85]
Created materials have no thumbnail

**Comment by jdent02** [comment]
This has to do with the appleseed bin path being erased when certain modules in the addon are updated.  Once you relink the bin directory the preview works.  Suggest closing this one.

**Comment by dictoon** [comment]
> This has to do with the appleseed bin path being erased when certain modules in the addon are updated.

Is there something we can do on our side?

**Comment by jdent02** [comment]
I'm not sure.  I think it's a problem similar to the one with EnumProperties.

**Comment by jdent02** [comment]
This one hasn't reared it's head in a while.  Can we close it?

**Comment by dictoon** [comment]
> This one hasn't reared it's head in a while. Can we close it?

I think so yes, especially since with the upcoming appleseed.python-based version of blenderseed, there's no longer any appleseed bin path setting, right?

**Comment by jdent02** [comment]
Yep, it’lol all be bundled together.

Closing.
