### ISSUE TITLE
Glass BSDF render dark inside another glass material

### ISSUE THREAD

**Issue by vallmoy** [appleseedhq/blenderseed#88]
![glass bsdf](https://user-images.githubusercontent.com/30292603/33611152-b065f284-d9cd-11e7-8c2f-5a2c6a22ba13.png)

![glass bsdf 2](https://user-images.githubusercontent.com/30292603/33611356-6d09601a-d9ce-11e7-87a2-fceefc95f12a.png)

[Glass.zip](https://github.com/appleseedhq/blenderseed/files/1531337/Glass.zip)

**Comment by jdent02** [comment]
else:
            # Need to iterate through layers only once, to find out if we have any btdfs.
            for layer in layers:
                if layer.bsdf_type in ['specular_btdf', 'diffuse_btdf']:
                    front_material_name = material.name + "_front"
                    back_material_name = material.name + "_back"
                    self.__emit_front_material(material, front_material_name, scene, layers)
                    self.__emit_back_material(material, back_material_name, scene, layers)
                    break

Is glass supposed to be in here too?

**Comment by dictoon** [comment]
@jdent02 I think so yes. I'm afraid there are a few places where this list exists, you should check... We'll refactor this at some point.

**Comment by jdent02** [comment]
I'll run some tests later.  Might just be coder error on this one.

**Comment by dictoon** [comment]
Looks like a bug in the Glass BSDF itself, replacing this issue by this one in appleseed core: https://github.com/appleseedhq/appleseed/issues/1756
