### ISSUE TITLE
Metal BRDF normal reflectance bug

### ISSUE THREAD

**Issue by vallmoy** [appleseedhq/blenderseed#98]
Random bug, unable to reproduce

![metal_normal_reflectance_color_bug](https://user-images.githubusercontent.com/30292603/33715285-518884a8-db52-11e7-9cd9-13e1aba6ff48.jpg)

**Comment by dictoon** [comment]
Is there anything the System Console when that happens?

**Comment by vallmoy** [comment]
Error: Could not open mat_preview.appleseed for writing

I am unable to reproduce this for now.

**Comment by dictoon** [comment]
Cannot repro.
